run:
  timeout: 20m
  disable-all: true
  tests: true

linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - decorder
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - execinquery
    - exportloopref
    - forcetypeassert
    - gci
    - goconst
    - gocritic
    - gofumpt
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacebloat
    - loggercheck
    - maintidx
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nolintlint
    - nosprintfhostport
    - predeclared
    - promlinter
    - reassign
    - revive
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tenv
    - testableexamples
    - thelper
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - whitespace

issues:
  max-same-issues: 0

linters-settings:
  gci:
    sections:
      - standard # Standard section: captures all standard packages.
      - default # Default section: contains all imports that could not be matched to another section type.
      - blank # blank imports
      - dot # dot imports
      - prefix(github.com/cometbft/cometbft) # comet
      - prefix(github.com/cosmos) # cosmos
      - prefix(cosmossdk.io) #cosmossdk.io
      - prefix(github.com/cosmos/cosmos-sdk) #cosmos-sdk
      - prefix(github.com/Stride-Labs) # stride

