version: "3"

services:

  stride:
    image: stridezone:localstride
    build:
      context: ../../../
      args:
        RUNNER_IMAGE: alpine:3.16
        GO_VERSION: 1.19
    volumes:
      - ./scripts/start.sh:/home/stride/start.sh
      - ./scripts/testnetify.py:/home/stride/testnetify.py
      - ./state_export.json:/home/stride/state_export.json
      - $HOME/.stride/:/home/stride/.stride/
    entrypoint:
      - /home/stride/start.sh
    environment:
      - MONIKER=val
      - CHAIN_ID=localstride
      - PERSISTENT_PEER=83bef603d202a9e2be41396ad4184f73ccba1a58@stride2:26658
    ports:
      - 26657:26657
      - 26656:26656
      - 1317:1317
      - 9090:9090
      - 9091:9091

  stride2:
    image: stridezone:localstride
    build:
      context: ../../../
      args:
        RUNNER_IMAGE: alpine:3.16
        GO_VERSION: 1.19
    volumes:
      - ./scripts/start.sh:/home/stride/start.sh
      - ./scripts/testnetify.py:/home/stride/testnetify.py
      - ./state_export.json:/home/stride/state_export.json
      - $HOME/.stride2/:/home/stride/.stride2/
    entrypoint:
      - /home/stride/start.sh
    environment:
      - MONIKER=val
      - CHAIN_ID=localstride
      - MNEMONIC=moral abandon vast load where nuclear doctor pottery fork thrive shoulder marble shaft ignore echo habit goddess sudden scout volume castle street duck school
      - PERSISTENT_PEER=0a7da08b1685a63bf2afc5b74385cad2340a8731@stride:26656
      - STRIDE_HOME=/home/stride/.stride2
    ports:
      - 26658:26656