version: "3"

services:

  stride:
    image: stridezone:localstride
    build:
      args:
        context: ../../../
        RUNNER_IMAGE: alpine:3.16
        GO_VERSION: 1.19
    volumes:
      - /home/kentgang/stride/testutil/localstride/state-export/scripts/start1.sh:/home/stride/start.sh
      - /home/kentgang/stride/testutil/localstride/state-export/scripts/testnetify.py:/home/stride/testnetify.py
      - /home/kentgang/stride/testutil/localstride/state-export/state_export.json:/home/stride/state_export.json
      - /home/kentgang/.stride/:/home/stride/.stride/
    command:
      - sudo
      - /bin/bash
      - /home/stride/start.sh
    environment:
      - MONIKER=val
      - CHAIN_ID=localstride
      - PERSISTENT_PEER=e7302c9e6ece271e2c3667d45114a05977e6eb1d@stride2:26658
      - STRIDE_HOME=/home/stride/.stride
    ports:
      - 26657:26657
      - 26656:26656
      - 1317:1317
      - 9090:9090
      - 9091:9091

  stride2:
    image: stridezone:localstride
    build:
      args:
        context: ../../../
        RUNNER_IMAGE: alpine:3.16
        GO_VERSION: 1.19
    volumes:
      - /home/kentgang/stride/testutil/localstride/state-export/scripts/start.sh:/home/stride/start.sh
      - /home/kentgang/stride/testutil/localstride/state-export/scripts/testnetify.py:/home/stride/testnetify.py
      - /home/kentgang/stride/testutil/localstride/state-export/state_export.json:/home/stride/state_export.json
      - /home/kentgang/.stride2/:/home/stride/.stride2/
    command:
      - sudo
      - /bin/bash
      - /home/stride/start.sh
    environment:
      - MONIKER=val
      - CHAIN_ID=localstride
      - MNEMONIC=moral abandon vast load where nuclear doctor pottery fork thrive shoulder marble shaft ignore echo habit goddess sudden scout volume castle street duck school
      - PERSISTENT_PEER=0a7da08b1685a63bf2afc5b74385cad2340a8731@stride:26656
      - STRIDE_HOME=/home/stride/.stride2
    ports:
      - 26658:26656
